# frozen_string_literal: true

require "samagotchi/tool_call_parser"
require "samagotchi/model_profile"
require "samagotchi/llm/openai_chat"
require "samagotchi/llm/native_tool_normalizer"

# The internal call each model format builds for each built-in tool, as
# data: [label, format, tool, input, expected call]. Gemma's input is the
# body between call:NAME{ and }; Qwen's the whole <tool_call> block;
# chat's the arguments the adapter parsed. A change to how calls are
# built shows up as an edited row here.
RSpec.describe "Tool call characterization" do
  gemma = Samagotchi::ToolCallParser::Gemma.new(Samagotchi::ModelProfile.gemma4)
  qwen = Samagotchi::ToolCallParser::Qwen.new(Samagotchi::ModelProfile.qwen36)

  define_method(:build) do |format, tool, input|
    case format
    when :gemma then gemma.parse("<|tool_call>call:#{tool}{#{input}}<tool_call|>").first
    when :qwen then qwen.parse(input).first
    when :chat
      call = Samagotchi::LLM::ToolCall.new(id: "c1", name: tool, arguments: input)
      Samagotchi::LLM::NativeToolNormalizer.normalize(call)
    end
  end

  rows = [
    ["execute all", :gemma, "execute",
     "command:<|\"|>ls -la<|\"|>,cwd:<|\"|>web<|\"|>",
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: "web"}],
    ["execute all", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=command>\nls -la\n</parameter>\n<parameter=cwd>\nweb\n</parameter>\n</function>\n</tool_call>",
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: "web"}],
    ["execute all", :chat, "execute",
     {"command" => "ls -la", "cwd" => "web"},
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: "web"}],
    ["execute required", :gemma, "execute",
     "command:<|\"|>ls<|\"|>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["execute required", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=command>\nls\n</parameter>\n</function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["execute required", :chat, "execute",
     {"command" => "ls"},
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["execute whitespace", :gemma, "execute",
     "command:<|\"|>  ls  <|\"|>,cwd:<|\"|> web <|\"|>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: "web"}],
    ["execute whitespace", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=command>\n  ls  \n</parameter>\n<parameter=cwd>\n web \n</parameter>\n</function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: "web"}],
    ["execute whitespace", :chat, "execute",
     {"command" => "  ls  ", "cwd" => " web "},
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: "web"}],
    ["execute extra key", :gemma, "execute",
     "command:<|\"|>ls<|\"|>,bogus:<|\"|>x<|\"|>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["execute extra key", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=command>\nls\n</parameter>\n<parameter=bogus>\nx\n</parameter>\n</function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["execute extra key", :chat, "execute",
     {"command" => "ls", "bogus" => "x"},
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["read all", :gemma, "read",
     "path:<|\"|>a.rb<|\"|>,start_line:<|\"|>3<|\"|>,end_line:<|\"|>9<|\"|>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: "9"}],
    ["read all", :qwen, "read",
     "<tool_call>\n<function=read>\n<parameter=path>\na.rb\n</parameter>\n<parameter=start_line>\n3\n</parameter>\n<parameter=end_line>\n9\n</parameter>\n</function>\n</tool_call>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: "9"}],
    ["read all", :chat, "read",
     {"path" => "a.rb", "start_line" => "3", "end_line" => "9"},
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: "9"}],
    ["read required", :gemma, "read",
     "path:<|\"|>a.rb<|\"|>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: nil, end_line: nil}],
    ["read required", :qwen, "read",
     "<tool_call>\n<function=read>\n<parameter=path>\na.rb\n</parameter>\n</function>\n</tool_call>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: nil, end_line: nil}],
    ["read required", :chat, "read",
     {"path" => "a.rb"},
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: nil, end_line: nil}],
    ["read whitespace", :gemma, "read",
     "path:<|\"|> a.rb <|\"|>,start_line:<|\"|> 3 <|\"|>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: nil}],
    ["read whitespace", :qwen, "read",
     "<tool_call>\n<function=read>\n<parameter=path>\n a.rb \n</parameter>\n<parameter=start_line>\n 3 \n</parameter>\n</function>\n</tool_call>",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: nil}],
    ["read whitespace", :chat, "read",
     {"path" => " a.rb ", "start_line" => " 3 "},
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: nil}],
    ["write all", :gemma, "write",
     "path:<|\"|>a.txt<|\"|>,content:<|\"|>hi\n<|\"|>",
     {name: "write", content: "hi\n", path: "a.txt", scope: nil}],
    ["write all", :qwen, "write",
     "<tool_call>\n<function=write>\n<parameter=path>\na.txt\n</parameter>\n<parameter=content>\nhi\n\n</parameter>\n</function>\n</tool_call>",
     {name: "write", content: "hi\n", path: "a.txt", scope: nil}],
    ["write all", :chat, "write",
     {"path" => "a.txt", "content" => "hi\n"},
     {name: "write", content: "hi\n", path: "a.txt", scope: nil}],
    ["write alias text", :gemma, "write",
     "path:<|\"|>a.txt<|\"|>,text:<|\"|>hi<|\"|>",
     {name: "write", content: "hi", path: "a.txt", scope: nil}],
    ["write alias text", :qwen, "write",
     "<tool_call>\n<function=write>\n<parameter=path>\na.txt\n</parameter>\n<parameter=text>\nhi\n</parameter>\n</function>\n</tool_call>",
     {name: "write", content: "hi", path: "a.txt", scope: nil}],
    ["write alias text", :chat, "write",
     {"path" => "a.txt", "text" => "hi"},
     {name: "write", content: "hi", path: "a.txt", scope: nil}],
    ["write missing content", :gemma, "write",
     "path:<|\"|>a.txt<|\"|>",
     {name: "write", content: nil, path: "a.txt", scope: nil}],
    ["write missing content", :qwen, "write",
     "<tool_call>\n<function=write>\n<parameter=path>\na.txt\n</parameter>\n</function>\n</tool_call>",
     {name: "write", content: nil, path: "a.txt", scope: nil}],
    ["write missing content", :chat, "write",
     {"path" => "a.txt"},
     {name: "write", content: nil, path: "a.txt", scope: nil}],
    ["write whitespace", :gemma, "write",
     "path:<|\"|> a.txt <|\"|>,content:<|\"|>  x  \n<|\"|>",
     {name: "write", content: "  x  \n", path: "a.txt", scope: nil}],
    ["write whitespace", :qwen, "write",
     "<tool_call>\n<function=write>\n<parameter=path>\n a.txt \n</parameter>\n<parameter=content>\n  x  \n\n</parameter>\n</function>\n</tool_call>",
     {name: "write", content: "  x  \n", path: "a.txt", scope: nil}],
    ["write whitespace", :chat, "write",
     {"path" => " a.txt ", "content" => "  x  \n"},
     {name: "write", content: "  x  \n", path: "a.txt", scope: nil}],
    ["memory_read all", :gemma, "memory_read",
     "name:<|\"|>foo<|\"|>,scope:<|\"|>project<|\"|>",
     {name: "memory_read", content: "foo", path: nil, scope: "project"}],
    ["memory_read all", :qwen, "memory_read",
     "<tool_call>\n<function=memory_read>\n<parameter=name>\nfoo\n</parameter>\n<parameter=scope>\nproject\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_read", content: "foo", path: nil, scope: "project"}],
    ["memory_read all", :chat, "memory_read",
     {"name" => "foo", "scope" => "project"},
     {name: "memory_read", content: "foo", path: nil, scope: "project"}],
    ["memory_read required", :gemma, "memory_read",
     "name:<|\"|>foo<|\"|>",
     {name: "memory_read", content: "foo", path: nil, scope: nil}],
    ["memory_read required", :qwen, "memory_read",
     "<tool_call>\n<function=memory_read>\n<parameter=name>\nfoo\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_read", content: "foo", path: nil, scope: nil}],
    ["memory_read required", :chat, "memory_read",
     {"name" => "foo"},
     {name: "memory_read", content: "foo", path: nil, scope: nil}],
    ["memory_write all", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,content:<|\"|>c<|\"|>,scope:<|\"|>system<|\"|>,description:<|\"|>d<|\"|>,current_model_only:<|\"|>true<|\"|>",
     {name: "memory_write", content: "c", path: "n", scope: "system", description: "d", current_model_only: "true"}],
    ["memory_write all", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\nn\n</parameter>\n<parameter=content>\nc\n</parameter>\n<parameter=scope>\nsystem\n</parameter>\n<parameter=description>\nd\n</parameter>\n<parameter=current_model_only>\ntrue\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: "c", path: "n", scope: "system", description: "d", current_model_only: "true"}],
    ["memory_write all", :chat, "memory_write",
     {"name" => "n", "content" => "c", "scope" => "system", "description" => "d", "current_model_only" => "true"},
     {name: "memory_write", content: "c", path: "n", scope: "system", description: "d", current_model_only: "true"}],
    ["memory_write alias text", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,text:<|\"|>c<|\"|>,scope:<|\"|>project<|\"|>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias text", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\nn\n</parameter>\n<parameter=text>\nc\n</parameter>\n<parameter=scope>\nproject\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias text", :chat, "memory_write",
     {"name" => "n", "text" => "c", "scope" => "project"},
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias body", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,body:<|\"|>c<|\"|>,scope:<|\"|>project<|\"|>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias body", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\nn\n</parameter>\n<parameter=body>\nc\n</parameter>\n<parameter=scope>\nproject\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias body", :chat, "memory_write",
     {"name" => "n", "body" => "c", "scope" => "project"},
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias value", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,value:<|\"|>c<|\"|>,scope:<|\"|>project<|\"|>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias value", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\nn\n</parameter>\n<parameter=value>\nc\n</parameter>\n<parameter=scope>\nproject\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write alias value", :chat, "memory_write",
     {"name" => "n", "value" => "c", "scope" => "project"},
     {name: "memory_write", content: "c", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write missing content", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,scope:<|\"|>project<|\"|>",
     {name: "memory_write", content: nil, path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write missing content", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\nn\n</parameter>\n<parameter=scope>\nproject\n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: nil, path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write missing content", :chat, "memory_write",
     {"name" => "n", "scope" => "project"},
     {name: "memory_write", content: nil, path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write whitespace", :gemma, "memory_write",
     "name:<|\"|> n <|\"|>,content:<|\"|>  c  <|\"|>,scope:<|\"|> project <|\"|>",
     {name: "memory_write", content: "  c  ", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write whitespace", :qwen, "memory_write",
     "<tool_call>\n<function=memory_write>\n<parameter=name>\n n \n</parameter>\n<parameter=content>\n  c  \n</parameter>\n<parameter=scope>\n project \n</parameter>\n</function>\n</tool_call>",
     {name: "memory_write", content: "  c  ", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["memory_write whitespace", :chat, "memory_write",
     {"name" => " n ", "content" => "  c  ", "scope" => " project "},
     {name: "memory_write", content: "  c  ", path: "n", scope: "project", description: nil, current_model_only: nil}],
    ["edit exact", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,old_text:<|\"|>foo<|\"|>,new_text:<|\"|>bar<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit exact", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=old_text>\nfoo\n</parameter>\n<parameter=new_text>\nbar\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit exact", :chat, "edit",
     {"path" => "a.rb", "old_text" => "foo", "new_text" => "bar"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit aliases", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,old:<|\"|>foo<|\"|>,new:<|\"|>bar<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit aliases", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=old>\nfoo\n</parameter>\n<parameter=new>\nbar\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit aliases", :chat, "edit",
     {"path" => "a.rb", "old" => "foo", "new" => "bar"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: "bar", start_line: nil, end_line: nil}],
    ["edit range", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,new_text:<|\"|>x\n<|\"|>,start_line:<|\"|>2<|\"|>,end_line:<|\"|>4<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "x\n", start_line: "2", end_line: "4"}],
    ["edit range", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=new_text>\nx\n\n</parameter>\n<parameter=start_line>\n2\n</parameter>\n<parameter=end_line>\n4\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "x\n", start_line: "2", end_line: "4"}],
    ["edit range", :chat, "edit",
     {"path" => "a.rb", "new_text" => "x\n", "start_line" => "2", "end_line" => "4"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "x\n", start_line: "2", end_line: "4"}],
    ["edit missing new_text", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,old_text:<|\"|>foo<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: nil, start_line: nil, end_line: nil}],
    ["edit missing new_text", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=old_text>\nfoo\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: nil, start_line: nil, end_line: nil}],
    ["edit missing new_text", :chat, "edit",
     {"path" => "a.rb", "old_text" => "foo"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "foo", new_text: nil, start_line: nil, end_line: nil}],
    ["edit missing old_text", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,new_text:<|\"|>bar<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "bar", start_line: nil, end_line: nil}],
    ["edit missing old_text", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=new_text>\nbar\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "bar", start_line: nil, end_line: nil}],
    ["edit missing old_text", :chat, "edit",
     {"path" => "a.rb", "new_text" => "bar"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: nil, new_text: "bar", start_line: nil, end_line: nil}],
    ["edit tags in old", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,old_text:<|\"|>a</old>b<new>c<|\"|>,new_text:<|\"|>d<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "a</old>b<new>c", new_text: "d", start_line: nil, end_line: nil}],
    ["edit tags in old", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=old_text>\na</old>b<new>c\n</parameter>\n<parameter=new_text>\nd\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "a</old>b<new>c", new_text: "d", start_line: nil, end_line: nil}],
    ["edit tags in old", :chat, "edit",
     {"path" => "a.rb", "old_text" => "a</old>b<new>c", "new_text" => "d"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "a</old>b<new>c", new_text: "d", start_line: nil, end_line: nil}],
    ["edit multi-line", :gemma, "edit",
     "path:<|\"|>a.rb<|\"|>,old_text:<|\"|>  one\n  two\n<|\"|>,new_text:<|\"|>  three\n<|\"|>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "  one\n  two\n", new_text: "  three\n", start_line: nil, end_line: nil}],
    ["edit multi-line", :qwen, "edit",
     "<tool_call>\n<function=edit>\n<parameter=path>\na.rb\n</parameter>\n<parameter=old_text>\n  one\n  two\n\n</parameter>\n<parameter=new_text>\n  three\n\n</parameter>\n</function>\n</tool_call>",
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "  one\n  two\n", new_text: "  three\n", start_line: nil, end_line: nil}],
    ["edit multi-line", :chat, "edit",
     {"path" => "a.rb", "old_text" => "  one\n  two\n", "new_text" => "  three\n"},
     {name: "edit", content: "", path: "a.rb", scope: nil, old_text: "  one\n  two\n", new_text: "  three\n", start_line: nil, end_line: nil}],
    ["task_create all", :gemma, "task_create",
     "command:<|\"|>sleep 5<|\"|>,cwd:<|\"|>web<|\"|>,env:<|\"|>{\"A\":\"1\"}<|\"|>",
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: "web", env: "{\"A\":\"1\"}"}],
    ["task_create all", :qwen, "task_create",
     "<tool_call>\n<function=task_create>\n<parameter=command>\nsleep 5\n</parameter>\n<parameter=cwd>\nweb\n</parameter>\n<parameter=env>\n{\"A\":\"1\"}\n</parameter>\n</function>\n</tool_call>",
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: "web", env: "{\"A\":\"1\"}"}],
    ["task_create all", :chat, "task_create",
     {"command" => "sleep 5", "cwd" => "web", "env" => "{\"A\":\"1\"}"},
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: "web", env: "{\"A\":\"1\"}"}],
    ["task_create required", :gemma, "task_create",
     "command:<|\"|>sleep 5<|\"|>",
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: nil, env: nil}],
    ["task_create required", :qwen, "task_create",
     "<tool_call>\n<function=task_create>\n<parameter=command>\nsleep 5\n</parameter>\n</function>\n</tool_call>",
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: nil, env: nil}],
    ["task_create required", :chat, "task_create",
     {"command" => "sleep 5"},
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: nil, env: nil}],
    ["task_get id", :gemma, "task_get",
     "id:<|\"|>abc<|\"|>",
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get id", :qwen, "task_get",
     "<tool_call>\n<function=task_get>\n<parameter=id>\nabc\n</parameter>\n</function>\n</tool_call>",
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get id", :chat, "task_get",
     {"id" => "abc"},
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get task_id", :gemma, "task_get",
     "task_id:<|\"|>abc<|\"|>",
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get task_id", :qwen, "task_get",
     "<tool_call>\n<function=task_get>\n<parameter=task_id>\nabc\n</parameter>\n</function>\n</tool_call>",
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get task_id", :chat, "task_get",
     {"task_id" => "abc"},
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["task_get both", :gemma, "task_get",
     "id:<|\"|>A<|\"|>,task_id:<|\"|>B<|\"|>",
     {name: "task_get", content: "A", path: nil, scope: nil}],
    ["task_get both", :qwen, "task_get",
     "<tool_call>\n<function=task_get>\n<parameter=id>\nA\n</parameter>\n<parameter=task_id>\nB\n</parameter>\n</function>\n</tool_call>",
     {name: "task_get", content: "A", path: nil, scope: nil}],
    ["task_get both", :chat, "task_get",
     {"id" => "A", "task_id" => "B"},
     {name: "task_get", content: "A", path: nil, scope: nil}],
    ["task_stop id", :gemma, "task_stop",
     "id:<|\"|>abc<|\"|>",
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_stop id", :qwen, "task_stop",
     "<tool_call>\n<function=task_stop>\n<parameter=id>\nabc\n</parameter>\n</function>\n</tool_call>",
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_stop id", :chat, "task_stop",
     {"id" => "abc"},
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_stop task_id", :gemma, "task_stop",
     "task_id:<|\"|>abc<|\"|>",
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_stop task_id", :qwen, "task_stop",
     "<tool_call>\n<function=task_stop>\n<parameter=task_id>\nabc\n</parameter>\n</function>\n</tool_call>",
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_stop task_id", :chat, "task_stop",
     {"task_id" => "abc"},
     {name: "task_stop", content: "abc", path: nil, scope: nil}],
    ["task_wait all", :gemma, "task_wait",
     "task_id:<|\"|>abc<|\"|>,timeout:<|\"|>30<|\"|>,tail_lines:<|\"|>5<|\"|>,done_pattern:<|\"|>ready <|\"|>",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: "30", tail_lines: "5", done_pattern: "ready"}],
    ["task_wait all", :qwen, "task_wait",
     "<tool_call>\n<function=task_wait>\n<parameter=task_id>\nabc\n</parameter>\n<parameter=timeout>\n30\n</parameter>\n<parameter=tail_lines>\n5\n</parameter>\n<parameter=done_pattern>\nready \n</parameter>\n</function>\n</tool_call>",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: "30", tail_lines: "5", done_pattern: "ready"}],
    ["task_wait all", :chat, "task_wait",
     {"task_id" => "abc", "timeout" => "30", "tail_lines" => "5", "done_pattern" => "ready "},
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: "30", tail_lines: "5", done_pattern: "ready"}],
    ["task_wait id", :gemma, "task_wait",
     "id:<|\"|>abc<|\"|>",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_wait id", :qwen, "task_wait",
     "<tool_call>\n<function=task_wait>\n<parameter=id>\nabc\n</parameter>\n</function>\n</tool_call>",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_wait id", :chat, "task_wait",
     {"id" => "abc"},
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_wait both", :gemma, "task_wait",
     "id:<|\"|>A<|\"|>,task_id:<|\"|>B<|\"|>",
     {name: "task_wait", content: "A", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_wait both", :qwen, "task_wait",
     "<tool_call>\n<function=task_wait>\n<parameter=id>\nA\n</parameter>\n<parameter=task_id>\nB\n</parameter>\n</function>\n</tool_call>",
     {name: "task_wait", content: "A", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_wait both", :chat, "task_wait",
     {"id" => "A", "task_id" => "B"},
     {name: "task_wait", content: "A", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["task_list none", :gemma, "task_list",
     "",
     {name: "task_list", content: "", path: nil, scope: nil}],
    ["task_list none", :qwen, "task_list",
     "<tool_call>\n<function=task_list>\n</function>\n</tool_call>",
     {name: "task_list", content: "", path: nil, scope: nil}],
    ["task_list none", :chat, "task_list",
     {},
     {name: "task_list", content: "", path: nil, scope: nil}],
    ["web_fetch all", :gemma, "web_fetch",
     "url:<|\"|>https://example.com<|\"|>",
     {name: "web_fetch", content: "https://example.com", path: nil, scope: nil}],
    ["web_fetch all", :qwen, "web_fetch",
     "<tool_call>\n<function=web_fetch>\n<parameter=url>\nhttps://example.com\n</parameter>\n</function>\n</tool_call>",
     {name: "web_fetch", content: "https://example.com", path: nil, scope: nil}],
    ["web_fetch all", :chat, "web_fetch",
     {"url" => "https://example.com"},
     {name: "web_fetch", content: "https://example.com", path: nil, scope: nil}],
    ["register_reminder all", :gemma, "register_reminder",
     "name:<|\"|>r<|\"|>,description:<|\"|>d<|\"|>,interval_minutes:<|\"|>5<|\"|>",
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: "5"}],
    ["register_reminder all", :qwen, "register_reminder",
     "<tool_call>\n<function=register_reminder>\n<parameter=name>\nr\n</parameter>\n<parameter=description>\nd\n</parameter>\n<parameter=interval_minutes>\n5\n</parameter>\n</function>\n</tool_call>",
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: "5"}],
    ["register_reminder all", :chat, "register_reminder",
     {"name" => "r", "description" => "d", "interval_minutes" => "5"},
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: "5"}],
    ["register_reminder missing interval", :gemma, "register_reminder",
     "name:<|\"|>r<|\"|>,description:<|\"|>d<|\"|>",
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: nil}],
    ["register_reminder missing interval", :qwen, "register_reminder",
     "<tool_call>\n<function=register_reminder>\n<parameter=name>\nr\n</parameter>\n<parameter=description>\nd\n</parameter>\n</function>\n</tool_call>",
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: nil}],
    ["register_reminder missing interval", :chat, "register_reminder",
     {"name" => "r", "description" => "d"},
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: "d", interval_minutes: nil}],
    ["cancel_reminder all", :gemma, "cancel_reminder",
     "name:<|\"|>r<|\"|>",
     {name: "cancel_reminder", content: "r", path: nil, scope: nil}],
    ["cancel_reminder all", :qwen, "cancel_reminder",
     "<tool_call>\n<function=cancel_reminder>\n<parameter=name>\nr\n</parameter>\n</function>\n</tool_call>",
     {name: "cancel_reminder", content: "r", path: nil, scope: nil}],
    ["cancel_reminder all", :chat, "cancel_reminder",
     {"name" => "r"},
     {name: "cancel_reminder", content: "r", path: nil, scope: nil}],
    ["list_reminders none", :gemma, "list_reminders",
     "",
     {name: "list_reminders", content: "", path: nil, scope: nil}],
    ["list_reminders none", :qwen, "list_reminders",
     "<tool_call>\n<function=list_reminders>\n</function>\n</tool_call>",
     {name: "list_reminders", content: "", path: nil, scope: nil}],
    ["list_reminders none", :chat, "list_reminders",
     {},
     {name: "list_reminders", content: "", path: nil, scope: nil}],
    ["list_sessions cwd", :gemma, "list_sessions",
     "cwd:<|\"|>/work<|\"|>",
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: "/work"}],
    ["list_sessions cwd", :qwen, "list_sessions",
     "<tool_call>\n<function=list_sessions>\n<parameter=cwd>\n/work\n</parameter>\n</function>\n</tool_call>",
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: "/work"}],
    ["list_sessions cwd", :chat, "list_sessions",
     {"cwd" => "/work"},
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: "/work"}],
    ["list_sessions none", :gemma, "list_sessions",
     "",
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: nil}],
    ["list_sessions none", :qwen, "list_sessions",
     "<tool_call>\n<function=list_sessions>\n</function>\n</tool_call>",
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: nil}],
    ["list_sessions none", :chat, "list_sessions",
     {},
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: nil}],
    ["send_note all", :gemma, "send_note",
     "session:<|\"|>3f2a<|\"|>,text:<|\"|> the API moved \n<|\"|>",
     {name: "send_note", content: "the API moved", path: nil, scope: nil, session: "3f2a"}],
    ["send_note all", :qwen, "send_note",
     "<tool_call>\n<function=send_note>\n<parameter=session>\n3f2a\n</parameter>\n<parameter=text>\n the API moved \n\n</parameter>\n</function>\n</tool_call>",
     {name: "send_note", content: "the API moved", path: nil, scope: nil, session: "3f2a"}],
    ["send_note all", :chat, "send_note",
     {"session" => "3f2a", "text" => " the API moved \n"},
     {name: "send_note", content: "the API moved", path: nil, scope: nil, session: "3f2a"}],
    ["send_note missing session", :gemma, "send_note",
     "text:<|\"|>hi<|\"|>",
     {name: "send_note", content: "hi", path: nil, scope: nil, session: nil}],
    ["send_note missing session", :qwen, "send_note",
     "<tool_call>\n<function=send_note>\n<parameter=text>\nhi\n</parameter>\n</function>\n</tool_call>",
     {name: "send_note", content: "hi", path: nil, scope: nil, session: nil}],
    ["send_note missing session", :chat, "send_note",
     {"text" => "hi"},
     {name: "send_note", content: "hi", path: nil, scope: nil, session: nil}],
    ["delegate all", :gemma, "delegate",
     "task:<|\"|>count<|\"|>,model:<|\"|>tiny<|\"|>,session:<|\"|>3f2a<|\"|>,wait:<|\"|>false<|\"|>,timeout:<|\"|>30<|\"|>",
     {name: "delegate", content: "count", path: nil, scope: nil, model: "tiny", session: "3f2a", wait: "false", timeout: "30"}],
    ["delegate all", :qwen, "delegate",
     "<tool_call>\n<function=delegate>\n<parameter=task>\ncount\n</parameter>\n<parameter=model>\ntiny\n</parameter>\n<parameter=session>\n3f2a\n</parameter>\n<parameter=wait>\nfalse\n</parameter>\n<parameter=timeout>\n30\n</parameter>\n</function>\n</tool_call>",
     {name: "delegate", content: "count", path: nil, scope: nil, model: "tiny", session: "3f2a", wait: "false", timeout: "30"}],
    ["delegate all", :chat, "delegate",
     {"task" => "count", "model" => "tiny", "session" => "3f2a", "wait" => "false", "timeout" => "30"},
     {name: "delegate", content: "count", path: nil, scope: nil, model: "tiny", session: "3f2a", wait: "false", timeout: "30"}],
    ["delegate required", :gemma, "delegate",
     "task:<|\"|>count<|\"|>",
     {name: "delegate", content: "count", path: nil, scope: nil, model: nil, session: nil, wait: nil, timeout: nil}],
    ["delegate required", :qwen, "delegate",
     "<tool_call>\n<function=delegate>\n<parameter=task>\ncount\n</parameter>\n</function>\n</tool_call>",
     {name: "delegate", content: "count", path: nil, scope: nil, model: nil, session: nil, wait: nil, timeout: nil}],
    ["delegate required", :chat, "delegate",
     {"task" => "count"},
     {name: "delegate", content: "count", path: nil, scope: nil, model: nil, session: nil, wait: nil, timeout: nil}],
    ["delegate_result all", :gemma, "delegate_result",
     "session:<|\"|>3f2a<|\"|>,timeout:<|\"|>30<|\"|>",
     {name: "delegate_result", content: "", path: nil, scope: nil, session: "3f2a", timeout: "30"}],
    ["delegate_result all", :qwen, "delegate_result",
     "<tool_call>\n<function=delegate_result>\n<parameter=session>\n3f2a\n</parameter>\n<parameter=timeout>\n30\n</parameter>\n</function>\n</tool_call>",
     {name: "delegate_result", content: "", path: nil, scope: nil, session: "3f2a", timeout: "30"}],
    ["delegate_result all", :chat, "delegate_result",
     {"session" => "3f2a", "timeout" => "30"},
     {name: "delegate_result", content: "", path: nil, scope: nil, session: "3f2a", timeout: "30"}],
    ["delegate_result none", :gemma, "delegate_result",
     "",
     {name: "delegate_result", content: "", path: nil, scope: nil, session: nil, timeout: nil}],
    ["delegate_result none", :qwen, "delegate_result",
     "<tool_call>\n<function=delegate_result>\n</function>\n</tool_call>",
     {name: "delegate_result", content: "", path: nil, scope: nil, session: nil, timeout: nil}],
    ["delegate_result none", :chat, "delegate_result",
     {},
     {name: "delegate_result", content: "", path: nil, scope: nil, session: nil, timeout: nil}],
    ["ask_user_question all", :gemma, "ask_user_question",
     "question:<|\"|>Pick?<|\"|>,options:<|\"|>[\"a\",\"b\"]<|\"|>,header:<|\"|>H<|\"|>,multi_select:<|\"|>true<|\"|>,allow_freeform:<|\"|>false<|\"|>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: "H", multi_select: "true", allow_freeform: "false"}],
    ["ask_user_question all", :qwen, "ask_user_question",
     "<tool_call>\n<function=ask_user_question>\n<parameter=question>\nPick?\n</parameter>\n<parameter=options>\n[\"a\",\"b\"]\n</parameter>\n<parameter=header>\nH\n</parameter>\n<parameter=multi_select>\ntrue\n</parameter>\n<parameter=allow_freeform>\nfalse\n</parameter>\n</function>\n</tool_call>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: "H", multi_select: "true", allow_freeform: "false"}],
    ["ask_user_question all", :chat, "ask_user_question",
     {"question" => "Pick?", "options" => "[\"a\",\"b\"]", "header" => "H", "multi_select" => "true", "allow_freeform" => "false"},
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: "H", multi_select: "true", allow_freeform: "false"}],
    ["ask_user_question options noise", :gemma, "ask_user_question",
     "question:<|\"|>Pick?<|\"|>,options:<|\"|>[a, b]<|\"|>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["ask_user_question options noise", :qwen, "ask_user_question",
     "<tool_call>\n<function=ask_user_question>\n<parameter=question>\nPick?\n</parameter>\n<parameter=options>\n[a, b]\n</parameter>\n</function>\n</tool_call>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["ask_user_question options noise", :chat, "ask_user_question",
     {"question" => "Pick?", "options" => "[a, b]"},
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["ask_user_question missing options", :gemma, "ask_user_question",
     "question:<|\"|>Pick?<|\"|>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: nil, header: nil, multi_select: nil, allow_freeform: nil}],
    ["ask_user_question missing options", :qwen, "ask_user_question",
     "<tool_call>\n<function=ask_user_question>\n<parameter=question>\nPick?\n</parameter>\n</function>\n</tool_call>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: nil, header: nil, multi_select: nil, allow_freeform: nil}],
    ["ask_user_question missing options", :chat, "ask_user_question",
     {"question" => "Pick?"},
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: nil, header: nil, multi_select: nil, allow_freeform: nil}],
    ["echo_args plugin", :gemma, "echo_args",
     "text:<|\"|>hi<|\"|>,times:<|\"|>3<|\"|>",
     {name: "echo_args", content: '{"text":"hi","times":"3"}', path: nil, scope: nil, args: {"text" => "hi", "times" => "3"}}],
    ["echo_args plugin", :qwen, "echo_args",
     "<tool_call>\n<function=echo_args>\n<parameter=text>\nhi\n</parameter>\n<parameter=times>\n3\n</parameter>\n</function>\n</tool_call>",
     # content is the params Hash's #to_s, whose spacing changed in Ruby 3.4 ("a" => 1 vs "a"=>1).
     {name: "echo_args", content: '{"text":"hi","times":"3"}', path: nil, scope: nil, args: {"text" => "hi", "times" => "3"}}],
    ["echo_args plugin", :chat, "echo_args",
     {"text" => "hi", "times" => "3"},
     {name: "echo_args", content: '{"text":"hi","times":"3"}', path: nil, scope: nil, args: {"text" => "hi", "times" => "3"}}],
    ["gemma: execute double-quoted escapes", :gemma, "execute",
     "command:\"grep \\\"\\d\\\" x\\n\"",
     {name: "execute", content: "grep \"\\d\" x", path: nil, scope: nil, cwd: nil}],
    ["gemma: execute single-quoted", :gemma, "execute",
     "command:'ls -la'",
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: nil}],
    ["gemma: execute unquoted prefix", :gemma, "execute",
     "command:ls -la",
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: nil}],
    ["gemma: execute unparsed body", :gemma, "execute",
     "ls -la",
     {name: "execute", content: "ls -la", path: nil, scope: nil, cwd: nil}],
    ["gemma: task_create unquoted prefix", :gemma, "task_create",
     "command:sleep 5",
     {name: "task_create", content: "sleep 5", path: nil, scope: nil, cwd: nil, env: nil}],
    ["gemma: read bare numbers", :gemma, "read",
     "path:<|\"|>a.rb<|\"|>,start_line:3,end_line:9",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: "3", end_line: "9"}],
    ["gemma: read unparsed body", :gemma, "read",
     "a.rb",
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: nil, end_line: nil}],
    ["gemma: memory_read unparsed body", :gemma, "memory_read",
     "foo",
     {name: "memory_read", content: "foo", path: nil, scope: nil}],
    ["gemma: memory_write booleans bare", :gemma, "memory_write",
     "name:<|\"|>n<|\"|>,content:<|\"|>c<|\"|>,scope:<|\"|>system<|\"|>,current_model_only:true",
     {name: "memory_write", content: "c", path: "n", scope: "system", description: nil, current_model_only: "true"}],
    ["gemma: task_get unquoted task_id", :gemma, "task_get",
     "task_id:abc",
     {name: "task_get", content: "abc", path: nil, scope: nil}],
    ["gemma: task_wait unquoted id", :gemma, "task_wait",
     "id:abc",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["gemma: task_wait unquoted task_id", :gemma, "task_wait",
     "task_id:abc",
     {name: "task_wait", content: "abc", path: nil, scope: nil, timeout: nil, tail_lines: nil, done_pattern: nil}],
    ["gemma: web_fetch unquoted", :gemma, "web_fetch",
     "url:https://example.com",
     {name: "web_fetch", content: "https://example.com", path: nil, scope: nil}],
    ["gemma: register_reminder unquoted name", :gemma, "register_reminder",
     "name:r",
     {name: "register_reminder", content: "r", path: nil, scope: nil, description: nil, interval_minutes: nil}],
    ["gemma: list_sessions unquoted cwd", :gemma, "list_sessions",
     "cwd:/work",
     {name: "list_sessions", content: "", path: nil, scope: nil, cwd: "/work"}],
    ["gemma: delegate unquoted task", :gemma, "delegate",
     "task:count the specs",
     {name: "delegate", content: "count the specs", path: nil, scope: nil, model: nil, session: nil, wait: nil, timeout: nil}],
    ["gemma: ask question prefix kept whole", :gemma, "ask_user_question",
     "question:Pick one, options:[a,b]",
     {name: "ask_user_question", content: "question:Pick one, options:[a,b]", path: nil, scope: nil, question: "question:Pick one, options:[a,b]", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["gemma: ask options delimited array", :gemma, "ask_user_question",
     "question:<|\"|>Pick?<|\"|>,options:[<|\"|>a<|\"|>,<|\"|>b<|\"|>]",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["gemma: send_note delimiter in quoted value", :gemma, "send_note",
     "session:\"<|\"|>3f2a<|\"|>\",text:<|\"|>hi<|\"|>",
     {name: "send_note", content: "hi", path: nil, scope: nil, session: "<|"}],
    ["gemma: plugin nested values", :gemma, "echo_args",
     "text:<|\"|>hi<|\"|>,times:3,loud:true,tags:[<|\"|>a<|\"|>],opt:{k:<|\"|>v<|\"|>}",
     {name: "echo_args", content: '{"text":"hi","times":3,"loud":true,"tags":["a"],"opt":{"k":"v"}}', path: nil, scope: nil, args: {"text" => "hi", "times" => 3, "loud" => true, "tags" => ["a"], "opt" => {"k" => "v"}}}],
    ["gemma: plugin unparsable body", :gemma, "echo_args",
     "text:<|\"|>hi",
     {name: "echo_args", content: "text:hi", path: nil, scope: nil, args: {}}],
    ["qwen: execute arg_key style", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<arg_key>command</arg_key>\n<arg_value>ls</arg_value>\n<arg_key>cwd</arg_key>\n<arg_value>web</arg_value>\n</function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: "web"}],
    ["qwen: execute tight tags", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=command>ls</parameter></function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["qwen: execute uppercase parameter", :qwen, "execute",
     "<tool_call>\n<function=execute>\n<parameter=COMMAND>\nls\n</parameter>\n</function>\n</tool_call>",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["qwen: write content keeps inner blank lines", :qwen, "write",
     "<tool_call>\n<function=write>\n<parameter=path>\na.txt\n</parameter>\n<parameter=content>\n\n\nx\n\n\n</parameter>\n</function>\n</tool_call>",
     {name: "write", content: "\n\nx\n\n", path: "a.txt", scope: nil}],
    ["qwen: ask options bracket noise", :qwen, "ask_user_question",
     "<tool_call>\n<function=ask_user_question>\n<parameter=question>\nPick?\n</parameter>\n<parameter=options>\n]\n</parameter>\n</function>\n</tool_call>",
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: "]", header: nil, multi_select: nil, allow_freeform: nil}],
    ["chat: read typed lines", :chat, "read",
     {"path" => "a.rb", "start_line" => 3, "end_line" => 9},
     {name: "read", content: "a.rb", path: nil, scope: nil, start_line: 3, end_line: 9}],
    ["chat: task_create env hash", :chat, "task_create",
     {"command" => "ls", "env" => {"A" => "1"}},
     {name: "task_create", content: "ls", path: nil, scope: nil, cwd: nil, env: {"A" => "1"}}],
    ["chat: ask options array", :chat, "ask_user_question",
     {"question" => "Pick?", "options" => ["a", "b"]},
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: ["a", "b"], header: nil, multi_select: nil, allow_freeform: nil}],
    ["chat: ask options unparseable string", :chat, "ask_user_question",
     {"question" => "Pick?", "options" => "]"},
     {name: "ask_user_question", content: "Pick?", path: nil, scope: nil, question: "Pick?", options: "]", header: nil, multi_select: nil, allow_freeform: nil}],
    ["chat: delegate typed wait/timeout", :chat, "delegate",
     {"task" => "count", "wait" => false, "timeout" => 30},
     {name: "delegate", content: "count", path: nil, scope: nil, model: nil, session: nil, wait: false, timeout: 30}],
    ["chat: memory_write typed boolean", :chat, "memory_write",
     {"name" => "n", "content" => "c", "scope" => "system", "current_model_only" => true},
     {name: "memory_write", content: "c", path: "n", scope: "system", description: nil, current_model_only: true}],
    ["chat: execute JSON-string arguments", :chat, "execute",
     "{\"command\":\"ls\"}",
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["chat: execute nil arguments", :chat, "execute",
     nil,
     {name: "execute", content: "", path: nil, scope: nil, cwd: nil}],
    ["chat: execute non-JSON string arguments", :chat, "execute",
     "ls -la",
     {name: "execute", content: "", path: nil, scope: nil, cwd: nil}],
    ["chat: execute env (not in schema)", :chat, "execute",
     {"command" => "ls", "env" => {"A" => "1"}},
     {name: "execute", content: "ls", path: nil, scope: nil, cwd: nil}],
    ["chat: plugin typed args", :chat, "echo_args",
     {"text" => "hi", "times" => 3},
     {name: "echo_args", content: '{"text":"hi","times":3}', path: nil, scope: nil, args: {"text" => "hi", "times" => 3}}],
  ].freeze

  rows.each do |label, format, tool, input, expected|
    it "#{format}: #{label}" do
      expect(build(format, tool, input)).to eq(expected)
    end
  end
end
